### ISSUE TITLE
Bot token should be private

### ISSUE THREAD

**Issue by danbst** [ArtaTwin/YBAGA_bot#3]
It is currently open to all

https://github.com/ArtaTwin/YBAGA_bot/blob/main/Trevoga_bot.py#L7

1. Create `secrets.py` file locally and add it to `.gitignore`
2. In secrets file create a variable with real token, import `secrets` in main code and use token from that variable
3. Change token in BotFather (because it is already in Git history)
4. Send me new token so I can update deployment

**Comment by danbst** [comment]
https://github.com/ArtaTwin/YBAGA_bot/blob/main/update_situation.py#L10

one more token

**Comment by ArtaTwin** [comment]
fixed
